CMakeLists.txt
README.md
data/org.pantheon.calculator.appdata.xml.in
data/org.pantheon.calculator.desktop.in.in
src/PantheonCalculator.vala

* Binary
* App ID
* Install dir
* Gettext

RDNN most of the things

---

src/MainWindow.vala

Set has_subtitle to false

---

CMakeLists.txt
data/io.elementary.calculator.gschema.xml
src/MainWindow.vala

It's just saved states, no real data to lose here

RDNN gschema

---

src/MainWindow.vala
src/PantheonCalculator.vala

Added undo feature (#5)

---

src/HistoryDialog.vala
src/MainWindow.vala

Updates the history window after calculations
Fixes #18

Update history dialog after calculations

---

src/PantheonCalculator.vala

The about dialog was previously removed by #24

Remove fields for deprecated about dialog

---

src/Core/Evaluation.vala
src/Core/Scanner.vala
src/HistoryDialog.vala
src/MainWindow.vala

Thanks to vala-lint 😉  Lots of missing brackets and a few tabs to spaces.

Code style

---

AUTHORS
src/Button.vala
src/Core/Evaluation.vala
src/Core/Scanner.vala
src/Core/Token.vala
src/HistoryDialog.vala
src/MainWindow.vala
src/PantheonCalculator.vala
test/CoreTest.vala

I've updated copyright headers and further code style, in particular for line length and comments.

Copyright header & code style

---

src/Core/Scanner.vala
test/CoreTest.vala

This fixes issue #59 and adds a few tests.

Fix next minus number / operator bug

---

src/PantheonCalculator.vala

`add_accelerator` is deprecated. replace with `set_accels_for_action`
Also use `var` and connect signals at the end

Fix deprecated warning with action accel

---

src/Core/Scanner.vala
test/CoreTest.vala

This fixes #57.
Added in some tests too!

Mismatched parenthesis on the left side now throws an error.

---

src/PantheonCalculator.vala

As we're transitioning away from `Granite.Application`
Fixes #81

Move from Granite.Application to Gtk.Application

---

src/MainWindow.vala

* Signals at the end
* Reduce variable scope

MainWindow: Get rid of single-use methods

---

flatpak/io.elementary.calculator.json

Added flatpak manifest

---

src/MainWindow.vala

Fix for selection and replace

---

src/MainWindow.vala

Lays the groundwork for adding other shortcuts too

MainWindow: Use GLib.Action for clear

---

data/io.elementary.calculator.appdata.xml.in

Insert valid (temporary) version and date for next release following request from @decathorpe 
These will have to be updated if and when further changes are added.

Insert valid version and temporary date for future release

---

data/io.elementary.calculator.appdata.xml.in
meson.build

https://github.com/elementary/calculator/compare/1.5.4...release-1.5.5

Release 1.5.5

---

debian/rules

Install for extra is set to false

Rules: don't override autoinstall

---

data/io.elementary.calculator.appdata.xml.in
src/Core/Evaluation.vala
src/MainWindow.vala
test/CoreTest.vala

I have added log button for both log 2 base 10 and normal log .
And added sin , cos and tan inverse functions . also added a inverse function to calculate 1/X .
I had also included test for these

Added log button and Trignometric Inverse Functions

---

src/MainWindow.vala

Fix #131 (this also applies to the entry when selecting smaller text option).

Fix for layout misplacement

---

.github/workflows/main.yml

We can run tests inside the sandbox now, so let's enable them :)
```
[0/1] Running all tests.
1/1 Calculator core test                    OK       0.01 s 
Ok:                    1
Expected Fail:         0
Fail:                  0
Unexpected Pass:       0
Skipped:               0
Timeout:               0
```

CI: enable running tests with flatpak action

---

src/Core/Evaluation.vala
src/Core/Scanner.vala
src/Core/Token.vala
src/MainWindow.vala
test/CoreTest.vala

Fixes #153
Also improved clarity a little and fixed a couple of long lines.

Fix handling of negative decimal numbers with no leading digits

---

data/io.elementary.calculator.appdata.xml.in
meson.build

I've confirmed this still builds on Hera

Release 1.6.0

---

src/MainWindow.vala

Remember entry contents for first window only

---

.github/workflows/main.yml

CI: use the newest flatpak action

---

data/io.elementary.calculator.appdata.xml.in
meson.build

https://github.com/elementary/calculator/compare/1.6.0...master

Release 1.6.1

---

.github/workflows/merge.yml

We also don't need to run tests here since we run them in CI

Merge Action: Set branch to daily

---

meson.build
src/Config.vala.in
src/PantheonCalculator.vala
src/meson.build

To prevent the flatpaked version of the app always being shown in English
Borrowed [the code written by tintou](https://github.com/elementary/camera/commit/33c7e17003d1ead422345624633a4cf0726a6c93)

l10n: Correctly setup the locales

---

po/LINGUAS
po/extra/LINGUAS

Added the translation file for Panjab in Weblate (which had been requested by @elSolus) but it was incomplete

LINGUAS: Sort and add Panjab

---

README.md
meson.build
src/MainWindow.vala

- Use Hdy.ApplicationWindow
- Restructure code style
- Rephrase ANS button's tooltip (#149)

Use libhandy for rounded corners and minor cleanups

---

src/MainWindow.vala

MainWindow: Focus the entry by default

---

src/MainWindow.vala

MainWindow: Set title for Multitasking View

---

src/Button.vala
src/MainWindow.vala

Use GLib.Action with action targets for buttons.
This avoids conflating the button label with its function and uses the built-in mechanism for activating actions in this way instead of adding a property to a special button subclass
these are probably dumb action names, open to suggestions

Use GLib.Action for buttons

---

src/MainWindow.vala

No logic changes, just the namespace

MainWindow: inline namespace

---

data/io.elementary.calculator.appdata.xml.in
meson.build

Major version bump since we broke deps in a pretty big way
Tested in an OS 6 VM and it doesn't look broken there :+1:

Release 2.0.0

---

data/icons/128.svg
data/icons/16.svg
data/icons/24.svg
data/icons/32.svg
data/icons/48.svg
data/icons/64.svg

Same as https://github.com/elementary/icons/pull/1148/ but mint! Not sure which accent color I like more

Redesign app icon

---

README.md

Just something I noticed, follow-up to #234

Update screenshot filename in README.md

---

data/io.elementary.calculator.desktop.in

Update to look more like what appstream generator gives us with spaces between sections:
* Add desktop entry version
* Add SingleMainWindow to hint to the shell this app is multi-window
* Rename "NewWindow" action to "new-window" as recommended in https://github.com/elementary/dock/issues/77#issuecomment-1821781386

Desktop: organize, SingleMainWindow

---

data/calculator.metainfo.xml.in
meson.build

Bump to latest flatpak platform

Release 8.0.1
